name : My First Workflow
on : push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Welcome Message
        run: echo "My First Github Actios Jon"
      
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2

      - name: List Of Files
        run: ls 

      - name: Read File
        run: cat README.md