name: Triggers Example
on:
    workflow_dispatch: 
    # schedule:
    #     - cron: "*/1 * * * *"
    
jobs:
    print-message:
        runs-on: ubuntu-latest
        steps:
            - name: Print a message
              run: echo "Hello World"




